//
//  hitboxDefs.h
//  GO:SX v3
//
//  Created by Andre Kalisch on 25.01.17.
//  Copyright © 2017 Andre Kalisch. All rights reserved.
//

#ifndef hitboxDefs_h
#define hitboxDefs_h

enum HitboxList
{
    HITBOX_PELVIS,      // 0 BONE_PELVIS
    // HITBOX_L_THIGH,     // 1 BONE_L_THIGH
    // HITBOX_L_CALF,      // 2 BONE_L_CALF
    // HITBOX_R_THIGH,     // 3 BONE_R_THIGH
    // HITBOX_R_CALF,      // 4 BONE_R_CALF
    HITBOX_SPINE0,      // 5 BONE_SPINE0
    HITBOX_SPINE1,      // 6 BONE_SPINE1
    HITBOX_SPINE2,      // 7 BONE_SPINE2
    HITBOX_SPINE3,      // 8 BONE_SPINE3
    HITBOX_NECK,        // 9 BONE_NECK
    HITBOX_HEAD,        // 10 BONE_HEAD
    // HITBOX_L_UPPERARM,  // 11 BONE_L_UPPER_ARM
    // HITBOX_L_FOREARM,   // 12 BONE_L_FOREARM
    // HITBOX_R_UPPERARM,  // 13 BONE_R_UPPER_ARM
    // HITBOX_R_FOREARM,   // 14 BONE_R_FOREARM
    HITBOX_MAX,
};

enum BoneList
{
    BONE_PELVIS         = 2,
    BONE_SPINE0         = 3,
    BONE_SPINE1         = 4,
    BONE_SPINE2         = 5,
    BONE_SPINE3         = 6,
    BONE_NECK           = 7,
    BONE_HEAD           = 8,
    // BONE_L_UPPER_ARM    = 11,
    // BONE_L_FOREARM      = 12,
    // BONE_R_UPPER_ARM    = 41,
    // BONE_R_FOREARM      = 42,
    // BONE_L_THIGH        = 70,
    // BONE_L_CALF         = 71,
    // BONE_R_THIGH        = 77,
    // BONE_R_CALF         = 78,
    BONE_MAX
};

enum BoneMatrixList
{
    MATRIXBONE_PELVIS,
    MATRIXBONE_NONE,
    MATRIXBONE_NONE2,
    MATRIXBONE_SPINE1,
    MATRIXBONE_SPINE2,
    MATRIXBONE_SPINE3,
    MATRIXBONE_SPINE4,
    MATRIXBONE_NECK,
    MATRIXBONE_L_CLAVICLE,
    MATRIXBONE_L_UPPER_ARM,
    MATRIXBONE_L_FOREARM,
    MATRIXBONE_L_HAND,
    MATRIXBONE_HEAD,
    MATRIXBONE_FORWARD,
    MATRIXBONE_R_CLAVICLE,
    MATRIXBONE_R_UPPER_ARM,
    MATRIXBONE_R_FOREARM,
    MATRIXBONE_R_HAND,
    MATRIXBONE_WEAPON,
    MATRIXBONE_WEAPON_SLIDE,
    MATRIXBONE_WEAPON_R_HAND,
    MATRIXBONE_WEAPON_L_HAND,
    MATRIXBONE_WEAPON_CLIP1,
    MATRIXBONE_WEAPON_CLIP2,
    MATRIXBONE_SILENCER,
    MATRIXBONE_R_THIGH,
    MATRIXBONE_R_CALF,
    MATRIXBONE_R_FOOT,
    MATRIXBONE_L_THIGH,
    MATRIXBONE_L_CALF,
    MATRIXBONE_L_FOOT,
    MATRIXBONE_L_WEAPON_HAND,
    MATRIXBONE_R_WEAPON_HAND,
    MATRIXBONE_L_FORETWIST,
    MATRIXBONE_L_CALFTWIST,
    MATRIXBONE_R_CALFTWIST,
    MATRIXBONE_L_THIGHTWIST,
    MATRIXBONE_R_THIGHTWIST,
    MATRIXBONE_L_UPARMTWIST,
    MATRIXBONE_R_UPARMTWIST,
    MATRIXBONE_R_FORETWIST,
    MATRIXBONE_R_TOE,
    MATRIXBONE_L_TOE,
    MATRIXBONE_R_FINGER01,
    MATRIXBONE_R_FINGER02,
    MATRIXBONE_R_FINGER03,
    MATRIXBONE_R_FINGER04,
    MATRIXBONE_R_FINGER05,
    MATRIXBONE_R_FINGER06,
    MATRIXBONE_R_FINGER07,
    MATRIXBONE_R_FINGER08,
    MATRIXBONE_R_FINGER09,
    MATRIXBONE_R_FINGER10,
    MATRIXBONE_R_FINGER11,
    MATRIXBONE_R_FINGER12,
    MATRIXBONE_R_FINGER13,
    MATRIXBONE_R_FINGER14,
    MATRIXBONE_L_FINGER01,
    MATRIXBONE_L_FINGER02,
    MATRIXBONE_L_FINGER03,
    MATRIXBONE_L_FINGER04,
    MATRIXBONE_L_FINGER05,
    MATRIXBONE_L_FINGER06,
    MATRIXBONE_L_FINGER07,
    MATRIXBONE_L_FINGER08,
    MATRIXBONE_L_FINGER09,
    MATRIXBONE_L_FINGER10,
    MATRIXBONE_L_FINGER11,
    MATRIXBONE_L_FINGER12,
    MATRIXBONE_L_FINGER13,
    MATRIXBONE_L_FINGER14,
    MATRIXBONE_L_FINGER15,
    MATRIXBONE_R_FINGER15,
    MATRIXBONE_MAX
};

struct Hitbox_t
{
    int     iBone;
    Vector  vMin;
    Vector  vMax;
    void Setup(int bone, Vector min, Vector max) {
        iBone = bone;
        vMin = min;
        vMax = max;
    }
};

#endif /* hitboxDefs_h */
